### ISSUE TITLE
facenet model convert to tensorflow lite

### ISSUE THREAD

**Issue by haicongfu** [div1090/Face-Recognition-on-Android#4]
Hi, are you able to convert facenet model to tensorflow lite? I have been trying with tensorflow 1.12 but failed with several unsupported options from original graph.

**Comment by div1090** [comment]
Facenet on tensorflow-lite - get the converted model [here](https://drive.google.com/open?id=1ClJkipPrEY2sbVc_j2eZrXvokKBh3oHj)
The notebook used to convert the model [here](https://colab.research.google.com/drive/1JwDUAPYdR_jL2-YQeqpaCO3d0XN2Ar84)

**Comment by haicongfu** [comment]
Awesome, many thanks!

**Comment by haicongfu** [comment]
tested and worked well ! Suggest to normalize embeddings to be consistent with original facenet output

def l2_normalize(x, axis=-1, epsilon=1e-10):
    output = x / np.sqrt(np.maximum(np.sum(np.square(x), axis=axis, keepdims=True), epsilon))
    return output

def extract_features(filename):
   ....
    results = l2_normalize(results)
    return results

**Comment by div1090** [comment]
Yes! You are absolutely right. In the android app, I added this step but missed it in the notebook!

thanks for pointing it out @haicongfu :)

**Comment by tigerzhang** [comment]
@haicongfu Do you plan to open source your tensorflow lite version?

**Comment by haicongfu** [comment]
@tigerzhang I used notebook provided by @divSivasankaran  for testing tensorflow lite. I may start work on tensorflow lite facenet on Android and contribute to this project soon.
